"""
Permutation tests and rank effect sizes for ERPA analyses.

This module provides rank-based association statistics, condition-permutation
tests, and Mann-Whitney effect-size summaries for per-trial measures. The
functions are intended for comparing conditions within pooled trial data.
"""

import numpy as np
from scipy.stats import rankdata, mannwhitneyu, spearmanr

def _partial_stat(a, b, c):
    """
    Compute a rank partial correlation.

    Parameters
    ----------
    a : array-like
        First variable.
    b : array-like
        Second variable.
    c : array-like
        Control variable.

    Returns
    -------
    float
        Pearson correlation between rank residuals of ``a`` and ``b`` after
        linear adjustment for ranked ``c``.
    """
    ra, rb, rc = rankdata(a), rankdata(b), rankdata(c)
    ra = ra - np.polyval(np.polyfit(rc, ra, 1), rc)
    rb = rb - np.polyval(np.polyfit(rc, rb, 1), rc)
    return float(np.corrcoef(ra, rb)[0, 1])


def partial_spearman(a, b, c):
    """
    Compute a partial Spearman correlation with a p-value.

    Parameters
    ----------
    a : array-like
        First variable.
    b : array-like
        Second variable.
    c : array-like
        Control variable.

    Returns
    -------
    scipy.stats._stats_py.SignificanceResult
        Spearman correlation result for the rank residuals of ``a`` and ``b``
        after linear adjustment for ranked ``c``.
    """
    ra, rb, rc = rankdata(a), rankdata(b), rankdata(c)
    ra = ra - np.polyval(np.polyfit(rc, ra, 1), rc)
    rb = rb - np.polyval(np.polyfit(rc, rb, 1), rc)
    return spearmanr(ra, rb)


def rank_biserial(x1, x0):
    """
    Compute the rank-biserial correlation for two groups.

    Parameters
    ----------
    x1 : array-like
        Values from the first group.
    x0 : array-like
        Values from the second group.

    Returns
    -------
    float
        Rank-biserial correlation. Values range from ``-1`` to ``1``. Positive
        values indicate that ``x1`` tends to be larger than ``x0``. Returns
        ``numpy.nan`` if either group is empty.

    Notes
    -----
    The statistic is computed from the Mann-Whitney U statistic.
    """
    x1 = np.asarray(x1); x0 = np.asarray(x0)
    n1, n0 = len(x1), len(x0)
    if n1 < 1 or n0 < 1:
        return np.nan
    U = mannwhitneyu(x1, x0, alternative="two-sided").statistic
    return 2.0 * U / (n1 * n0) - 1.0


def perm_diff_partial(lag, lum, rt, cond, labels=("PBS", "MUS"),
                      n_perm=10000, seed=0):
    """
    Test whether a partial rank correlation differs between conditions.

    The statistic is the difference between two within-condition partial rank
    correlations. Each correlation relates ``lag`` to ``lum`` while controlling
    for ``rt``. The null distribution is generated by shuffling condition labels
    across pooled trials from the two requested conditions.

    Parameters
    ----------
    lag : array-like
        Per-trial lag values.
    lum : array-like
        Per-trial luminance or cue values.
    rt : array-like
        Per-trial reaction times used as the control variable.
    cond : array-like
        Condition label for each trial.
    labels : tuple of str, optional
        Two condition labels to compare. The reported difference is
        ``labels[0] - labels[1]``.
    n_perm : int, optional
        Number of condition-label permutations.
    seed : int, optional
        Random seed.

    Returns
    -------
    dict
        Dictionary with keys ``"r1"``, ``"r2"``, ``"diff"``, ``"p"``, and
        ``"null"``. ``"diff"`` is ``r1 - r2``.
    """
    lag, lum, rt, cond = (np.asarray(x) for x in (lag, lum, rt, cond))
    m1, m2 = cond == labels[0], cond == labels[1]
    r1 = _partial_stat(lag[m1], lum[m1], rt[m1])
    r2 = _partial_stat(lag[m2], lum[m2], rt[m2])
    d_obs = r1 - r2

    sel = m1 | m2
    L, M, T = lag[sel], lum[sel], rt[sel]
    n1, N = int(m1.sum()), int(sel.sum())
    rng = np.random.default_rng(seed)
    dd = np.empty(n_perm)
    for i in range(n_perm):
        p = rng.permutation(N)
        a, b = p[:n1], p[n1:]
        dd[i] = _partial_stat(L[a], M[a], T[a]) - _partial_stat(L[b], M[b], T[b])
    p_val = float((np.abs(dd) >= abs(d_obs)).mean())
    return dict(r1=r1, r2=r2, diff=d_obs, p=p_val, null=dd)


def perm_diff_biserial(lag, error, cond, labels=("PBS", "MUS"),
                       n_perm=10000, seed=0):
    """
    Test whether a rank-biserial effect differs between conditions.

    The statistic is the difference between two within-condition rank-biserial
    correlations. Within each condition, ``lag`` values from correct trials are
    compared with ``lag`` values from error trials. The null distribution is
    generated by shuffling condition labels while preserving each trial's outcome.

    Parameters
    ----------
    lag : array-like
        Per-trial lag values.
    error : array-like
        Per-trial outcome values, coded as ``1`` for error and ``0`` for correct.
    cond : array-like
        Condition label for each trial.
    labels : tuple of str, optional
        Two condition labels to compare. The reported difference is
        ``labels[0] - labels[1]``.
    n_perm : int, optional
        Number of condition-label permutations.
    seed : int, optional
        Random seed.

    Returns
    -------
    dict
        Dictionary with keys ``"r1"``, ``"r2"``, ``"diff"``, ``"p"``, and
        ``"null"``. ``"diff"`` is ``r1 - r2``.
    """
    lag, error, cond = (np.asarray(x) for x in (lag, error, cond))
    m1, m2 = cond == labels[0], cond == labels[1]
    r1 = rank_biserial(lag[m1 & (error == 0)], lag[m1 & (error == 1)])
    r2 = rank_biserial(lag[m2 & (error == 0)], lag[m2 & (error == 1)])
    d_obs = r1 - r2

    sel = m1 | m2
    L, H = lag[sel], error[sel]
    n1, N = int(m1.sum()), int(sel.sum())
    rng = np.random.default_rng(seed)
    dd = []
    for _ in range(n_perm):
        p = rng.permutation(N)
        a, b = p[:n1], p[n1:]
        ra = rank_biserial(L[a][H[a] == 1], L[a][H[a] == 0])
        rb = rank_biserial(L[b][H[b] == 1], L[b][H[b] == 0])
        if np.isnan(ra) or np.isnan(rb):
            continue
        dd.append(ra - rb)
    dd = np.asarray(dd)
    p_val = float((np.abs(dd) >= abs(d_obs)).mean())
    return dict(r1=r1, r2=r2, diff=d_obs, p=p_val, null=dd)


def condition_main_effect(values, cond, labels=("PBS", "MUS")):
    """
    Compare one per-trial measure between two conditions.

    Parameters
    ----------
    values : array-like
        Per-trial measure values.
    cond : array-like
        Condition label for each trial.
    labels : tuple of str, optional
        Two condition labels to compare.

    Returns
    -------
    dict
        Dictionary with the Mann-Whitney statistic, p-value, rank-biserial effect
        size, and group medians. Keys are ``"stat"``, ``"p"``, ``"effect"``,
        ``"median_1"``, and ``"median_2"``.
    """
    values, cond = np.asarray(values), np.asarray(cond)
    v1, v2 = values[cond == labels[0]], values[cond == labels[1]]
    U = mannwhitneyu(v1, v2, alternative="two-sided")
    return dict(stat=float(U.statistic), p=float(U.pvalue),
                effect=rank_biserial(v1, v2),
                median_1=float(np.median(v1)), median_2=float(np.median(v2)))


def perm_partial_p(lag, lum, rt, n_perm=10000, seed=0):
    """
    Compute a permutation p-value for one partial rank correlation.

    The observed statistic is the partial rank correlation between ``lag`` and
    ``lum`` while controlling for ``rt``. The null distribution is generated by
    shuffling ``lum`` while leaving ``lag`` and ``rt`` unchanged.

    Parameters
    ----------
    lag : array-like
        Per-trial lag values.
    lum : array-like
        Per-trial luminance or cue values.
    rt : array-like
        Per-trial reaction times used as the control variable.
    n_perm : int, optional
        Number of luminance-label permutations.
    seed : int, optional
        Random seed.

    Returns
    -------
    obs : float
        Observed partial rank correlation.
    p : float
        Two-sided permutation p-value.
    """
    lag, lum, rt = np.asarray(lag), np.asarray(lum), np.asarray(rt)
    obs = _partial_stat(lag, lum, rt)
    rng = np.random.default_rng(seed)
    null = np.empty(n_perm)
    for i in range(n_perm):
        null[i] = _partial_stat(lag, rng.permutation(lum), rt)
    return obs, float((np.abs(null) >= abs(obs)).mean())
